internal/controller/expected_netboxmock_calls_test.go
internal/controller/ipaddress_controller_test.go
internal/controller/ipaddressclaim_controller_test.go
internal/controller/netbox_testdata_test.go
internal/controller/suite_test.go

restructure controller tests to avoid race conditions and make it compatible with sigs.k8s.io/controller-runtime v0.19.0

Restructure the controller tests

---

api/v1/prefixclaim_types.go
internal/controller/ipaddressclaim_controller.go
internal/controller/ipaddressclaim_controller_test.go
internal/controller/prefixclaim_controller.go

Before this change the reconciliation of a claim resource wasn't triggered if a change was detected in the owned resource because of the missing controller reference in the owner reference
Changes:
Use an owner reference with a reference to a controller
Remove status update which is no longer needed in ip address claim controller test
Remove unused functions from prefix claim type

Trigger reconciliation of owner if change in controlled resource is detected

---

Makefile
internal/controller/ipaddress_controller.go
internal/controller/ipaddressclaim_controller.go
internal/controller/ipaddressclaim_helpers.go
internal/controller/prefix_controller.go
internal/controller/prefixclaim_controller.go
internal/controller/prefixclaim_helpers.go

- move the warning for ignored manually defined restoration hash to claim controller

Move the warning for ignored manually defined restoration hash to claim controller

---

internal/controller/ipaddress_controller.go
internal/controller/prefix_controller.go
pkg/config/config.go

Fixes #44
If HTTPS_ENABLE is set to false, .status.url now shows a correct http url

Fix the url in .status.url for both IpAddress and Prefix CRs

---

internal/controller/ipaddress_controller_test.go
internal/controller/ipaddressclaim_controller_test.go

Fixes flakiness described in #32 by moving to asynchronous check for the CR creation.

Fix integration tests

---

.github/workflows/build-image.yaml

- For PRs, `sha-[short sha value] will be used to tag the docker image, but the image will not be pushed to the GitHub Package Registry. 
- The SHA value is now taken from the HEAD commit of the PR that triggers the CI run
- When merging into the default branch (`main` for now), `latest` will be used to tag the docker image, along with the `sha-[short sha value]`. The image will be pushed to the GitHub Package Registry. 
A demo of the end result can be seen here https://github.com/henrybear327/netbox-operator/pkgs/container/netbox-operator/versions.
Reference:
- https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag

Improve image tagging

---

.github/workflows/build-image.yaml

Added the capability for the CI pipeline to generate docker images with git tags.
For example, if we tag a commit with `v0.0.1-alpha.1`, the docker images with the tag `v0.0.1-alpha.1` will be generated. 
You can see the effect here https://github.com/henrybear327/netbox-operator/pkgs/container/netbox-operator
Closes https://github.com/netbox-community/netbox-operator/issues/67

Generate docker images for tagged commits

---

.github/ISSUE_TEMPLATE/bug-report.yml

The default value of `# paste your configuration here` setting will make the rendered markdown ugly. 
Aligning it with `Relevant log output`

Update the bug report template

---

.github/workflows/build-image.yaml

There are 2 flavors of the image version tags. 
- For example, Prometheus images contain `:v.` [in the image tag](https://hub.docker.com/layers/prom/prometheus/v2.35.0/images/sha256-4b86ad59abc67fa19a6e1618e936f3fd0f6ae13f49260da55a03eeca763a0fb5)
- Ubuntu images [don't](https://hub.docker.com/_/ubuntu), which conforms to the [semver description](https://semver.org/#is-v123-a-semantic-version)
We will publish both for now and see how the usage turns out.

Generate docker images with and without prefixed v for tagged commits

---

internal/controller/ipaddress_controller.go
internal/controller/prefix_controller.go

In some cases, the Prefix and IpAddress reconcilers are stuck because a resource update prior to unlocking failed (e.g. due to concurrent edit in the kube-api). This could be e.g. the following line https://github.com/netbox-community/netbox-operator/blob/main/internal/controller/prefix_controller.go#L182
The next run of the reconciler will have `nil` for `ll` in https://github.com/netbox-community/netbox-operator/blob/main/internal/controller/prefix_controller.go#L203 and thus not try to unlock it. Example log output of the netbox-operator:
```
2024-09-12T11:48:16+02:00       ERROR   Reconciler error        {"controller": "prefix", "controllerGroup": "netbox.dev", "controllerKind": "Prefix", "Prefix": {"name":"example","namespace":"default"}, "namespace": "default", "name": "example", …
```

Make unlocking more reliable

---

api/v1/ipaddress_types.go
api/v1/ipaddressclaim_types.go
api/v1/prefix_types.go
api/v1/prefixclaim_types.go
config/crd/bases/netbox.dev_ipaddressclaims.yaml
config/crd/bases/netbox.dev_ipaddresses.yaml
config/crd/bases/netbox.dev_prefixclaims.yaml
config/crd/bases/netbox.dev_prefixes.yaml

A few UX changes:
- Adds an age column (with Kubebuilder this disappears from the CRD as soon as you add the first printcolumn)
- Orders the condition columns to feature the "Ready" condition as the last one
Before:
```bash
kubectl get ipc
NAME                    IPADDRESS    READY   IPASSIGNED
ipaddressclaim-sample   2.0.0.1/32   True    True
```
After:
```bash
kubectl get ipc
NAME                    IPADDRESS    IPASSIGNED   READY   AGE
ipaddressclaim-sample   2.0.0.1/32   True         True    4s
```

Add age column and fix column order

---

api/v1/ipaddress_types.go
api/v1/prefix_types.go
internal/controller/expected_netboxmock_calls_test.go
internal/controller/ipaddress_controller.go
internal/controller/ipaddress_controller_test.go
internal/controller/netbox_testdata_test.go
internal/controller/prefix_controller.go
pkg/netbox/api/ip_address.go
pkg/netbox/api/prefix.go

Changes:
* adding Finalizers are moved up
* IP/Prefix deletion functions are updated with not found errors
* error handling in Finalizers is updated with not found errors
* integration test is updated
Close #77

Fix Finalizers

---

CONTRIBUTING.md
README.md

To conform with the Swisscom FOSS compliance check

Reduce development-related content in README and move them to CONTRIBUTING.md

---

PROJECT

Fixes #66
New CRD's can be generated either without group name, like the existing ones or with group names by enabling multi-group support

removed group name from existing crd's

---

api/v1/prefix_types.go
api/v1/prefixclaim_types.go
config/crd/bases/netbox.dev_prefixclaims.yaml
config/crd/bases/netbox.dev_prefixes.yaml
config/samples/netbox_v1_prefix.yaml
config/samples/netbox_v1_prefixclaim.yaml
gen/mock_interfaces/netbox_mocks.go
internal/controller/prefixclaim_controller.go
internal/controller/prefixclaim_helpers.go
internal/controller/suite_test.go
pkg/netbox/api/client.go
pkg/netbox/api/ip_address_claim_test.go
pkg/netbox/api/prefix.go
pkg/netbox/api/prefix_claim.go
pkg/netbox/api/prefix_claim_test.go
pkg/netbox/api/prefix_test.go
pkg/netbox/api/site.go
pkg/netbox/api/site_test.go
pkg/netbox/api/tenancy_test.go
pkg/netbox/interfaces/netbox.go
pkg/netbox/models/ipam.go

Currently, the site that is set in a prefixclaim CR is not updated in NetBox. This PR focuses on fixing the underlying logic to ensure accurate updates.
Using the go-netbox client the site is not removed from the resource in NetBox with the IpamPrefixesUpdate function. To avoid inconsistent state between the Prefix CR and the Prefix Resource in NetBox a validation rule was added to the prefix type which does not allow the deletion of the site field once it was created.

Fix: add logic to update site of prefix in netbox

---

ParentPrefixSelectorGuide.md
api/v1/prefixclaim_types.go
config/crd/bases/netbox.dev_prefixclaims.yaml
config/samples/netbox_v1_prefixclaim_parentprefixselector.yaml
pkg/netbox/api/errors.go
pkg/netbox/api/prefix_claim.go

Added support for the built-in field `family` in `ParentPrefixSelector`.
The CR validation is also written to reject values besides `IPv4` and `IPv6`, when the key `family` is present in `ParentPrefixSelector`.
The documentation and the sample CR are also updated.

Add support for built-in field `family` in `ParentPrefixSelector`

---

kind/load-data-job/local-demo-data.sql

Alongside the IPv4 pools, we introduce IPv6 prefixes to the local demo data to make testing other operators easier.

Add a prefix with IPv6 addresses to local demo data

---

.github/workflows/build-image.yaml
.github/workflows/govuln.yaml
.github/workflows/integration-test.yaml
.github/workflows/lint.yaml
.github/workflows/unit-test.yaml

Reduce noise in the case that CI jobs failed when new commits are pushed before the previous one's CI job has finished

Cancel running workflow when new commits are pushed in a pull request

---

kind/local-env.sh

Sorry that https://github.com/netbox-community/netbox-operator/pull/162 broke the local setup, so we are reverting it.
We would investigate later why the CI is passing though.

Revert "Upgrade to using netbox-5.0.0-beta.161"

---

.github/env
.github/workflows/e2e-tests.yaml
.gitignore
CONTRIBUTING.md
Makefile
README.md
kind/load-data-job/local-demo-data.sql
tests/e2e/Prefix/IPv4/GivenPrefixClaimWhenAppliedThenFailedPrefixExhausted/chainsaw-test.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWhenAppliedThenFailedPrefixExhausted/netbox_v1_prefixclaim_1.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWhenAppliedThenFailedPrefixExhausted/netbox_v1_prefixclaim_2.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWhenAppliedThenFailedPrefixExhausted/netbox_v1_prefixclaim_3.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithIPv4ParentPrefixSelectorWhenAppliedThenSucceed/chainsaw-test.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithIPv4ParentPrefixSelectorWhenAppliedThenSucceed/netbox_v1_prefixclaim.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithPreserveWhenAppliedDeletedAppliedThenRestorationSucceed/chainsaw-test.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithPreserveWhenAppliedDeletedAppliedThenRestorationSucceed/netbox_v1_prefixclaim_1.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithPreserveWhenAppliedDeletedAppliedThenRestorationSucceed/netbox_v1_prefixclaim_2.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithPreserveWhenAppliedThenSucceed/chainsaw-test.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithPreserveWhenAppliedThenSucceed/netbox_v1_prefixclaim.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithPreserveWhenParentPrefixSelectorAppliedDeletedAppliedThenRestorationSucceed/chainsaw-test.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithPreserveWhenParentPrefixSelectorAppliedDeletedAppliedThenRestorationSucceed/netbox_v1_prefixclaim_1.yaml
tests/e2e/Prefix/IPv4/GivenPrefixClaimWithPreserveWhenParentPrefixSelectorAppliedDeletedAppliedThenRestorationSucceed/netbox_v1_prefixclaim_2.yaml
tests/e2e/Prefix/IPv6/GivenPrefixClaimWithIPv6ParentPrefixSelectorWhenAppliedThenSucceed/chainsaw-test.yaml
tests/e2e/Prefix/IPv6/GivenPrefixClaimWithIPv6ParentPrefixSelectorWhenAppliedThenSucceed/netbox_v1_prefixclaim.yaml
tests/e2e/README.md
tests/e2e/kind-config.yaml

Leveraging Chainsaw, we can easily write e2e tests for the NetBox operator, testing directly against the NetBox instance
This PR focuses solely on the Prefix and PrefixClaim, happy path.
Implements https://github.com/netbox-community/netbox-operator/issues/163

Add e2e tests for Prefix

---

.github/env
.github/workflows/e2e-tests.yaml
.gitignore
Makefile
kind/load-data-job/README.md
kind/load-data-job/dockerfile.orig
kind/load-data-job/load-data.orig.sh
kind/load-data-job/main.py
kind/local-env.sh

(Reopen https://github.com/netbox-community/netbox-operator/pull/167. Due to PR base branch setting errors, I can't reopen the original PR...)
Since we are introducing the e2e test and running against real NetBox instances, it makes sense to test against different versions of NetBox, so we can flag issues early on.
CI will now run all e2e tests against the supported versions.
The supported NetBox versions are (the latest patch version for the `major.minor` release):
- 3.7.8
- 4.0.11
- 4.1.8
Instead of `create-kind`, we now have `create-kind-3.7.8`, `create-kind-4.0.11`, and `create-kind-4.1.8`. The same goes for `make test-e2e`.
The patching mechanism is used to apply database schema fixes and demo data version changes. When we introduce support for new versions, usually only the database …

Support e2e tests against multiple NetBox versions

---

config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_service.yaml

add the 'app.kubernetes.io/part-of: netbox-operator' to the pod template and the metrics monitor service

Add part-of label to metrics monitor service labelSelector

---

.github/workflows/build-image.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/govuln.yaml
.github/workflows/integration-test.yaml
.github/workflows/lint.yaml
.github/workflows/unit-test.yaml

When we merge a PR into the main branch before the previously merged commit finishes, the CI jobs will be cancelled (see https://github.com/netbox-community/netbox-operator/commits/main/), which is not ideal as we would like to see if all commits merged into the main branch can pass CI checks.

[CI] Do not cancel concurrent CI jobs on main

---

.github/workflows/build-image.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/govuln.yaml
.github/workflows/integration-test.yaml
.github/workflows/lint.yaml
.github/workflows/unit-test.yaml

Revert https://github.com/netbox-community/netbox-operator/pull/160 (For some reason, https://github.com/netbox-community/netbox-operator/pull/221 fails to address the cancellation on CI runs against main branch).
Our docker images being pushed to the GitHub registry relies on the CI runs against the main branch, so we need to ensure that the CI runs on main branch is always running without any hiccups.

Fix CI runs being cancelled on main branch

---

pkg/netbox/api/client.go

add rest request towards netbox to monitoring

Add metrics for rest requests towards netbox

---

.github/workflows/e2e-tests.yaml

Kind clusters for the e2e tests are implicitly created in the `make test-e2e-*` targets that are triggered in the `Run e2e tests` steps of the `e2e-tests` pipeline. Thus, there is no need for the additional `Start kind cluster` step in the e2e tests pipeline. This PR removes the additional kind cluster creation.

Remove duplicate kind cluster creation

---

README.md
api/v1/ipaddress_types.go
api/v1/ipaddressclaim_types.go
api/v1/iprange_types.go
api/v1/iprangeclaim_types.go
api/v1/prefix_types.go
api/v1/prefixclaim_types.go
config/crd/bases/netbox.dev_ipaddressclaims.yaml
config/crd/bases/netbox.dev_ipaddresses.yaml
config/crd/bases/netbox.dev_iprangeclaims.yaml
config/crd/bases/netbox.dev_ipranges.yaml
config/crd/bases/netbox.dev_prefixclaims.yaml
config/crd/bases/netbox.dev_prefixes.yaml
config/samples/netbox_v1_prefixclaim_parentprefixselector.yaml
config/samples/netbox_v1_prefixclaim_parentprefixselector_bool_int.yaml

- Add more verbose CRD documentation
- Add Installation methods
- Add notes on Mixed usage of Prefixes
- Add FAQ
Fixes #128

Improve CRD documention

---

README.md
api/v1/ipaddress_types.go
api/v1/ipaddressclaim_types.go
api/v1/iprange_types.go
api/v1/iprangeclaim_types.go
api/v1/prefix_types.go
api/v1/prefixclaim_types.go
api/v1/shared_conditions.go
cmd/main.go
internal/controller/interfaces.go
internal/controller/ipaddress_controller.go
internal/controller/ipaddressclaim_controller.go
internal/controller/iprange_controller.go
internal/controller/iprangeclaim_controller.go
internal/controller/prefix_controller.go
internal/controller/prefixclaim_controller.go
internal/controller/suite_test.go
internal/controller/utils.go
tests/e2e/Prefix/IPv4/prefixclaim-ipv4-invalid-parentprefixselector/chainsaw-test.yaml
tests/e2e/Prefix/IPv4/prefixclaim-ipv4-prefixexhausted/chainsaw-test.yaml
tests/e2e/ipaddress/ipv4/ipaddressclaim-ipv4-prefixexhausted/chainsaw-test.yaml
tests/e2e/ipaddress/ipv6/ipaddressclaim-ipv6-prefixexhausted/chainsaw-test.yaml
tests/e2e/iprange/ipv4/iprangeclaim-ipv4-invalid-customfieldnotexisting/chainsaw-test.yaml
tests/e2e/iprange/ipv4/iprangeclaim-ipv4-invalid-customfieldwrongdatatype/chainsaw-test.yaml
tests/e2e/iprange/ipv4/iprangeclaim-ipv4-invalid-parentprefix/chainsaw-test.yaml
tests/e2e/iprange/ipv4/iprangeclaim-ipv4-invalid-tenant/chainsaw-test.yaml
tests/e2e/iprange/ipv4/iprangeclaim-ipv4-prefixexhausted/chainsaw-test.yaml
tests/e2e/iprange/ipv6/iprangeclaim-ipv6-prefixexhausted/chainsaw-test.yaml

This PR shows one way in which we can consolidate the reporting of status and conditions into a common function.
It exposes access to the EventRecorder so events can be emitted independently of condition updates, and also logs changes in conditions as well as errors.
Would be happy to receive feedback and take suggestions as to how we can improve this functionality.

Consolidate Status and Condition reporting

---

internal/controller/prefixclaim_controller.go

This PR fixes a panic that occurred if now matching parent prefix was found for a prefixclaim.

Distinguish if error occurd or if no matching prefix was found

---

kind/deploy-netbox.sh
kind/go.mod
kind/netbox-db/netbox-db.yaml

When deploying NetBox with `FORCE_NETBOX_NGINX_IPV4=true`, the script patches the NetBox `Deployment` to mount a custom `nginx-unit.json` config. This change triggers a new ReplicaSet and Pod, but the old ReplicaSet and its pod may linger during rollout.
Since the NetBox pod uses a PVC with `ReadWriteOnce` access mode, Kubernetes prevents simultaneous attachment to the new pod. This causes a volume `Multi-Attach` error and stalls the deployment.
- Identify the latest ReplicaSet owned by the `netbox` deployment
- Delete the older ReplicaSets to free any attached volumes

Cleanup old ReplicaSets after NetBox deployment patch to prevent volume Multi-Attach errors

---

.github/workflows/lint.yaml
docs/examples/README.md
docs/examples/example2-load-balancer-ip/README.md
docs/examples/example5-multicluster/zurich-pools.yaml
internal/controller/expected_netboxmock_calls_test.go
internal/controller/prefixclaim_controller.go
internal/controller/prefixclaim_helpers_test.go
pkg/netbox/api/ip_address_claim_test.go
pkg/netbox/api/ip_address_test.go
pkg/netbox/api/ip_range_claim_test.go
pkg/netbox/api/prefix_claim.go
pkg/netbox/api/prefix_test.go
pkg/netbox/api/site_test.go
tests/e2e/Prefix/IPv4/prefixclaim-ipv4-parentprefixselector-nonexisingcustomfield/chainsaw-test.yaml

Adds a codespell CI job and fixes current spelling issues using `codespell --skip="*.svg" --write-changes`

Add codespell CI job

---

api/v1/ipaddress_types.go
api/v1/ipaddressclaim_types.go
api/v1/iprange_types.go
api/v1/iprangeclaim_types.go
api/v1/prefix_types.go
api/v1/prefixclaim_types.go
internal/controller/ipaddress_controller.go
internal/controller/iprange_controller.go
internal/controller/prefix_controller.go
internal/controller/prefixclaim_controller.go

Alignment of controllers:
- o variable name
- spacing of kubebuilder markers
- RequeueAfter
- removal of some empty lines

Minor changes to align across controllers

---

.github/release.yml
.github/workflows/release.yaml
CHANGELOG.md
scripts/update-changelog-from-release.sh

Add automatic changelog generation to release workflow
This PR extends the automatic release workflow (#390) to include changelog generation.
- Added a step to automatically update CHANGELOG.md when creating releases
- Added script that fetches release notes from GitHub and updates the changelog

Adding automatic CHANGELOG generation

---

.github/workflows/release.yaml

correct image path in manager kustomization

Fix: correct image path in manager kustomization

---

kind/deploy-netbox.sh

fix typo in deploy-netbox.sh which causes the script to fail if a different registry is used

Fix typo in deploy-netbox.sh

---

config/manager/manager.yaml

Simple fix to add the `app.kubernetes.io/name: netbox-operator`  to the spec.selector so it can be used for filtering logs properly.

Adding app label to spec.selector
